name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: lein deps
    - uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2020.04.05'
    - name: Run linter
      run: clj-kondo --lint src
    - name: Run tests
      run: lein test
